spring.application.name=erp
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

app.admin.nome=${APP_ADMIN_NOME:Administrador}
app.admin.email=${APP_ADMIN_EMAIL:}
app.admin.senha=${APP_ADMIN_SENHA:}
