CREATE TABLE auditoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario VARCHAR(255) NOT NULL,
    data_hora TIMESTAMP NOT NULL,
    operacao VARCHAR(80) NOT NULL,
    entidade VARCHAR(120) NOT NULL,
    entidade_id VARCHAR(80),
    descricao VARCHAR(500)
);

CREATE INDEX idx_auditoria_data_hora ON auditoria (data_hora);
CREATE INDEX idx_auditoria_usuario ON auditoria (usuario);
CREATE INDEX idx_auditoria_entidade ON auditoria (entidade);
