CREATE TABLE clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_pessoa VARCHAR(20) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    documento VARCHAR(20) NOT NULL,
    email VARCHAR(255),
    telefone VARCHAR(30),
    logradouro VARCHAR(255),
    numero VARCHAR(30),
    cidade VARCHAR(120),
    estado VARCHAR(2),
    cep VARCHAR(12),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_cliente_documento UNIQUE (documento)
);

CREATE TABLE fornecedores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    documento VARCHAR(20) NOT NULL,
    email VARCHAR(255),
    telefone VARCHAR(30),
    logradouro VARCHAR(255),
    numero VARCHAR(30),
    cidade VARCHAR(120),
    estado VARCHAR(2),
    cep VARCHAR(12),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_fornecedor_documento UNIQUE (documento)
);

CREATE TABLE produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(80) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    categoria VARCHAR(120),
    unidade_medida VARCHAR(30) NOT NULL,
    preco_venda DECIMAL(19, 2) NOT NULL,
    custo DECIMAL(19, 2) NOT NULL,
    estoque_minimo DECIMAL(19, 3) NOT NULL DEFAULT 0,
    saldo_estoque DECIMAL(19, 3) NOT NULL DEFAULT 0,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_produto_codigo UNIQUE (codigo)
);

CREATE INDEX idx_produto_nome ON produtos (nome);
