CREATE TABLE movimentacoes_estoque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id BIGINT NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    quantidade DECIMAL(19, 3) NOT NULL,
    data_hora TIMESTAMP NOT NULL,
    origem VARCHAR(120) NOT NULL,
    usuario VARCHAR(255) NOT NULL,
    CONSTRAINT fk_movimentacao_produto FOREIGN KEY (produto_id) REFERENCES produtos (id)
);

CREATE INDEX idx_movimentacao_produto ON movimentacoes_estoque (produto_id);
CREATE INDEX idx_movimentacao_data_hora ON movimentacoes_estoque (data_hora);
