ALTER TABLE produtos ADD COLUMN gtin VARCHAR(14);
ALTER TABLE produtos ADD COLUMN descricao VARCHAR(1000);
ALTER TABLE produtos ADD COLUMN marca VARCHAR(255);
ALTER TABLE produtos ADD COLUMN subcategoria VARCHAR(120);
ALTER TABLE produtos ADD COLUMN estoque_maximo DECIMAL(19, 3) DEFAULT 0;
ALTER TABLE produtos ADD COLUMN localizacao VARCHAR(255);
