ALTER TABLE produtos ADD COLUMN foto_arquivo VARCHAR(255);

CREATE TABLE funcionarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    email VARCHAR(255),
    telefone VARCHAR(30),
    cargo VARCHAR(120) NOT NULL,
    data_nascimento DATE,
    data_admissao DATE NOT NULL,
    cep VARCHAR(8),
    logradouro VARCHAR(255),
    numero VARCHAR(50),
    complemento VARCHAR(120),
    bairro VARCHAR(120),
    cidade VARCHAR(120),
    estado VARCHAR(2),
    foto_arquivo VARCHAR(255),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_funcionario_cpf UNIQUE (cpf)
);
